"""Generate a local OAuth token for seo_agent.py.

Usage:
  python generate_seo_token.py --token token.json

If client_secret.json is not present, the script can reuse client_id/client_secret
from an existing token.json generated by google-auth-oauthlib.

Create the client secret in Google Cloud Console as an OAuth Desktop app, then
enable Google Search Console API, Google Analytics Data API, and Google Sheets API.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from google_auth_oauthlib.flow import InstalledAppFlow

from seo_agent import SCOPES, TOKEN_FILE


def _flow_from_client_config(client_secrets: str, token_path: str) -> InstalledAppFlow:
    secrets = Path(client_secrets)
    if secrets.exists():
        return InstalledAppFlow.from_client_secrets_file(str(secrets), SCOPES)

    token = Path(token_path)
    if token.exists():
        data = json.loads(token.read_text(encoding="utf-8"))
        if data.get("client_id") and data.get("client_secret"):
            return InstalledAppFlow.from_client_config({
                "installed": {
                    "client_id": data["client_id"],
                    "client_secret": data["client_secret"],
                    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                    "token_uri": data.get("token_uri") or "https://oauth2.googleapis.com/token",
                    "redirect_uris": ["http://localhost"],
                },
            }, SCOPES)

    raise SystemExit(
        f"Missing {client_secrets}. Provide --client-secrets, or run with an existing token.json "
        "that contains client_id/client_secret."
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate SEO OAuth token.json")
    parser.add_argument("--client-secrets", default="client_secret.json",
                        help="Path to OAuth Desktop client JSON from Google Cloud Console")
    parser.add_argument("--token", default=TOKEN_FILE,
                        help="Output token path, defaults to SEO_TOKEN_FILE or token.json")
    parser.add_argument("--no-browser", action="store_true",
                        help="Print the auth URL instead of opening a browser")
    args = parser.parse_args()

    flow = _flow_from_client_config(args.client_secrets, args.token)
    creds = flow.run_local_server(
        port=0,
        open_browser=not args.no_browser,
        access_type="offline",
        prompt="consent",
        include_granted_scopes="true",
    )

    if not creds.refresh_token:
        raise SystemExit(
            "No refresh_token returned. Re-run with prompt=consent, or remove the app grant "
            "from your Google Account and authorize again."
        )

    out = Path(args.token)
    out.write_text(creds.to_json(), encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
